### PR TITLE
Update base lib version in Paillier.cabal

### PR DESCRIPTION
**Pull request by colatkinson**
This allows the library to work with GHC 8.0.1

### CODE REVIEW

**Comment by onemouth** [comment]
Thanks! Let me merge into dev

**Comment by colatkinson** [comment]
What would the process be to update the package on Hackage? It would make it way easier to use the lib in a project I'm working on

**Comment by onemouth** [comment]
I will merge to release and update the package. Maybe today or tomorrow.

**Comment by onemouth** [comment]
It seems test cannot pass now... should fix it

**Pull request merged**
